package upgrade

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"
	"path"
	"time"

	"github.com/seventv/helm-manager/manager"
	"github.com/seventv/helm-manager/manager/types"
	"go.uber.org/zap"
	"gopkg.in/yaml.v3"
)

func HandleChart(chart types.Chart, envMap map[string]string, emptyHash bool) (types.ChartUpgrade, bool) {
	const (
		LOCK_IDX     = 0
		VALUES_IDX   = 1
		DEFAULTS_IDX = 2
	)
	values, err := manager.ReadChartValues(chart)
	if err == manager.ErrorNotFound {
		err = nil
		zap.S().Infof("No values file found for %s, assuming first time running", chart.Name)
	}
	if err != nil {
		zap.S().Error("Unable to parse values file for %s", chart.Name)
		return types.ChartUpgrade{}, false
	}

	if !values.IsZero() && values.Kind != yaml.DocumentNode {
		zap.S().Errorf("Invalid values file for %s", chart.Name)
		return types.ChartUpgrade{}, false
	}

	defaultChartValues := manager.GetDefaultChartValues(chart)
	if defaultChartValues.IsZero() {
		zap.S().Errorf("No default values found for %s", chart.Name)
		return types.ChartUpgrade{}, false
	}

	if len(values.Content) == 0 {
		values = yaml.Node{
			Kind: yaml.DocumentNode,
			Content: []*yaml.Node{{
				Kind:    yaml.MappingNode,
				Content: []*yaml.Node{},
				Tag:     "!!map",
			}, {
				Kind:    yaml.MappingNode,
				Content: []*yaml.Node{},
				Tag:     "!!map",
			}, &defaultChartValues},
		}
	} else if len(values.Content) == 1 {
		merged := manager.RemoveYamlComments(*values.Content[0])

		values.Content = []*yaml.Node{{
			Kind:    yaml.MappingNode,
			Content: []*yaml.Node{},
			Tag:     "!!map",
		}, &merged, &defaultChartValues}
	} else if len(values.Content) == 2 {
		values.Content = append(values.Content, &defaultChartValues)
	}

	if len(values.Content) != 3 {
		zap.S().Errorf("Invalid values file for %s", chart.Name)
		return types.ChartUpgrade{}, false
	}

	oldLock := types.ChartLock{}
	values.Content[LOCK_IDX].Decode(&oldLock)

	{
		merged := manager.PruneYaml(defaultChartValues, manager.MergeYaml(manager.RemoveYamlComments(*values.Content[DEFAULTS_IDX]), *values.Content[VALUES_IDX]))
		merged.HeadComment = "## This section contains the non-default values for this chart.\n## If you want to change a value, add it here.\n## If you want to reset a value to default, remove it here.\n## If you want to reset all values to default, delete this entire section.\n## You can also modify the section below, any changes there will be reset however they will be copied into this section.\n\n"

		values.Content[VALUES_IDX] = &merged
		values.Content[DEFAULTS_IDX] = &defaultChartValues
	}

	// marshal the full version without comments
	var envSubbedChartValuesData []byte
	{
		// remove all comments from the full version
		envSubbedChartValuesData, err = manager.MarshalYaml(manager.ToDocument(manager.RemoveYamlComments(manager.MergeYaml(*values.Content[DEFAULTS_IDX], *values.Content[VALUES_IDX]))))
		if err != nil {
			zap.S().Errorf("Failed to marshal values for %s", chart.Name)
			return types.ChartUpgrade{}, false
		}

		// substitute the env variables into the full version without comments
		for env, value := range envMap {
			envSubbedChartValuesData = bytes.ReplaceAll(envSubbedChartValuesData, []byte(fmt.Sprintf("${%s}", env)), []byte(value))
		}
	}

	// create a new lock entry
	lock := types.ChartLock{
		Version: chart.Version,
		Chart:   chart.Chart,
		Hash:    hex.EncodeToString(manager.Sum256(envSubbedChartValuesData)),
		Time:    time.Now(),
	}

	if emptyHash {
		lock.Hash = ""
	}

	{ // marshal the lock entry
		lockData, err := yaml.Marshal(lock)
		if err != nil {
			zap.S().Errorf("Failed to marshal lock for %s", chart.Name)
			return types.ChartUpgrade{}, false
		}

		lockNode := yaml.Node{}
		err = yaml.Unmarshal(lockData, &lockNode)
		if err != nil {
			zap.S().Errorf("Failed to unmarshal lock for %s", chart.Name)
			return types.ChartUpgrade{}, false
		}

		lockNode = manager.ConvertDocument(lockNode)
		lockNode.HeadComment = "## This section is automatically generated by helm-manager. DO NOT EDIT.\n\n"
		values.Content[LOCK_IDX] = &lockNode
	}

	// allow for showing only the values that changed from the defaults.
	chartValuesData, err := manager.MarshalYaml(values)
	if err != nil {
		zap.S().Errorf("Failed to marshal values for %s", chart.Name)
		return types.ChartUpgrade{}, false
	}

	// make sure the folder exists
	err = os.MkdirAll(path.Dir(chart.File), 0755)
	if err != nil {
		zap.S().Errorf("Failed to create folder for %s", chart.Name)
		return types.ChartUpgrade{}, false
	}

	err = os.WriteFile(chart.File, chartValuesData, 0644)
	if err != nil {
		zap.S().Errorf("Failed to write values for %s to %s", chart.Name, chart.File)
		return types.ChartUpgrade{}, false
	}

	return types.ChartUpgrade{
		Chart:            chart,
		ChartLock:        lock,
		OldLock:          oldLock,
		ValuesYaml:       chartValuesData,
		SubbedValuesYaml: envSubbedChartValuesData,
	}, true
}

func HandleUpgrade(cfg types.Config, upgrade types.ChartUpgrade) bool {
	zap.S().Infof("Upgrading %s", upgrade.Chart.Name)

	chart := upgrade.Chart

	var args []string
	if cfg.Arguments.Upgrade.GenerateTemplate {
		args = []string{
			"template",
			chart.Name, chart.Chart,
			"--namespace", chart.Namespace,
			"--version", chart.Version,
			"--values", "-",
			"--create-namespace",
			"--include-crds",
		}
	} else {
		args = []string{
			"upgrade", "--install",
			chart.Name, chart.Chart,
			"--namespace", chart.Namespace,
			"--values", "-",
			"--version", chart.Version,
			"--create-namespace",
		}

		if cfg.Arguments.Upgrade.Wait {
			args = append(args, "--wait")
		}

		if cfg.Arguments.Upgrade.Atomic {
			args = append(args, "--atomic")
		}

		if upgrade.ChartLock.Hash == upgrade.OldLock.Hash && upgrade.ChartLock.Version == upgrade.OldLock.Version && !cfg.Arguments.Upgrade.ForceCharts[chart.Name] {
			zap.S().Infof("Skipping %s for upgrade, no changes detected", chart.Name)
			return true
		}
	}

	if cfg.Arguments.Upgrade.DryRun {
		args = append(args, "--dry-run")
	}

	output, err := manager.ExecuteCommandStdin(bytes.NewReader(upgrade.SubbedValuesYaml), "helm", args...)
	if err != nil {
		zap.S().Errorf("Failed to upgrade chart %s\n%s", chart.Name, output)
		return false
	}

	if cfg.Arguments.Upgrade.GenerateTemplate {
		if cfg.Arguments.Upgrade.TemplateOutputDir != "" {
			err = os.MkdirAll(cfg.Arguments.Upgrade.TemplateOutputDir, 0755)
			if err != nil {
				zap.S().Error("Failed to create directory generated templates")
				return false
			}
		}

		err = os.WriteFile(path.Join(cfg.Arguments.Upgrade.TemplateOutputDir, fmt.Sprintf("%s-template.yaml", chart.Name)), output, 0644)
		if err != nil {
			zap.S().Errorf("Failed to write template file for %s", chart.Name)
			return false
		}

		zap.S().Infof("Generated template for %s", chart.Name)
	} else {
		zap.S().Infof("Successfully upgraded chart %s", chart.Name)
	}

	return true
}
